import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';

/**
 * Validate and normalize slide metadata for smart layout selection
 * Ensures all required fields are present with fallback values
 * 
 * This is a copy of the validation function from the route for testing purposes
 */
function validateAndNormalizeSlideMetadata(slide: any): any {
  const normalized = { ...slide };
  let hasWarnings = false;
  
  // Only validate content slides (title slides don't need layout metadata)
  if (slide.type !== "content") {
    return normalized;
  }
  
  // Validate and normalize semanticIntent
  if (!normalized.semanticIntent || typeof normalized.semanticIntent !== "string") {
    normalized.semanticIntent = "inform";
    hasWarnings = true;
  }
  
  // Validate and normalize visualStrategy
  if (!normalized.visualStrategy || typeof normalized.visualStrategy !== "object") {
    normalized.visualStrategy = {
      primary: "text-focused",
      pattern: "cards",
      emphasis: "clarity"
    };
    hasWarnings = true;
  } else {
    // Ensure all visualStrategy fields are present
    if (!normalized.visualStrategy.primary) {
      normalized.visualStrategy.primary = "text-focused";
      hasWarnings = true;
    }
    if (!normalized.visualStrategy.pattern) {
      normalized.visualStrategy.pattern = "cards";
      hasWarnings = true;
    }
    if (!normalized.visualStrategy.emphasis) {
      normalized.visualStrategy.emphasis = "clarity";
      hasWarnings = true;
    }
  }
  
  // Validate contentLayoutHint (optional but log if missing)
  if (!normalized.contentLayoutHint) {
    // Don't set fallback - this is truly optional and will be determined by content analysis
  }
  
  // Validate assets/image metadata (optional)
  if (normalized.assets?.image) {
    if (typeof normalized.assets.image.required !== "boolean") {
      normalized.assets.image.required = false;
    }
    if (!normalized.assets.image.orientation) {
      normalized.assets.image.orientation = "landscape";
    }
  }
  
  return normalized;
}

/**
 * Validate entire outline and normalize all slides
 */
function validateAndNormalizeOutline(outline: any): any {
  if (!outline.slides || !Array.isArray(outline.slides)) {
    throw new Error("Invalid outline structure: missing slides array");
  }
  
  return {
    ...outline,
    slides: outline.slides.map(validateAndNormalizeSlideMetadata)
  };
}

/**
 * **Feature: smart-layout-selection, Property 1: Metadata Completeness**
 * **Validates: Requirements 1.1, 1.2, 1.3, 1.4, 1.5, 1.6**
 * 
 * For any outline slide generated by the system, all required metadata fields 
 * (semanticIntent, visualStrategy, contentLayoutHint, assets) must be present 
 * with either LLM-provided values or system-generated fallback values.
 */
describe('Property 1: Metadata Completeness', () => {
  // Generator for content slides with partial metadata
  const partialContentSlideArb = fc.record({
    type: fc.constant("content" as const),
    title: fc.string({ minLength: 5, maxLength: 50 }),
    bulletPoints: fc.array(fc.string({ minLength: 10, maxLength: 100 }), { minLength: 2, maxLength: 6 }),
    // Randomly include or omit metadata fields
    semanticIntent: fc.option(fc.constantFrom("inform", "compare", "instruct", "emphasize", "narrate"), { nil: undefined }),
    visualStrategy: fc.option(
      fc.record({
        primary: fc.option(fc.constantFrom("diagram", "image", "mixed", "text-focused"), { nil: undefined }),
        pattern: fc.option(fc.constantFrom("cards", "grid", "flow", "split", "spotlight"), { nil: undefined }),
        emphasis: fc.option(fc.constantFrom("progression", "contrast", "relationship", "scale"), { nil: undefined }),
      }),
      { nil: undefined }
    ),
    contentLayoutHint: fc.option(
      fc.constantFrom("boxes", "bullets", "sequence", "steps", "quotes", "circles", "numbers"),
      { nil: undefined }
    ),
  });

  it('should ensure semanticIntent is always present after validation', () => {
    fc.assert(
      fc.property(partialContentSlideArb, (slide) => {
        const normalized = validateAndNormalizeSlideMetadata(slide);
        
        // semanticIntent must be present and be a string
        expect(normalized.semanticIntent).toBeDefined();
        expect(typeof normalized.semanticIntent).toBe('string');
        expect(normalized.semanticIntent.length).toBeGreaterThan(0);
      }),
      { numRuns: 100 }
    );
  });

  it('should ensure visualStrategy is always present with all required fields', () => {
    fc.assert(
      fc.property(partialContentSlideArb, (slide) => {
        const normalized = validateAndNormalizeSlideMetadata(slide);
        
        // visualStrategy must be present and be an object
        expect(normalized.visualStrategy).toBeDefined();
        expect(typeof normalized.visualStrategy).toBe('object');
        
        // All three fields must be present
        expect(normalized.visualStrategy.primary).toBeDefined();
        expect(typeof normalized.visualStrategy.primary).toBe('string');
        
        expect(normalized.visualStrategy.pattern).toBeDefined();
        expect(typeof normalized.visualStrategy.pattern).toBe('string');
        
        expect(normalized.visualStrategy.emphasis).toBeDefined();
        expect(typeof normalized.visualStrategy.emphasis).toBe('string');
      }),
      { numRuns: 100 }
    );
  });

  it('should preserve valid metadata when present', () => {
    fc.assert(
      fc.property(
        fc.record({
          type: fc.constant("content" as const),
          title: fc.string({ minLength: 5, maxLength: 50 }),
          bulletPoints: fc.array(fc.string({ minLength: 10, maxLength: 100 }), { minLength: 2, maxLength: 6 }),
          semanticIntent: fc.constantFrom("inform", "compare", "instruct", "emphasize", "narrate"),
          visualStrategy: fc.record({
            primary: fc.constantFrom("diagram", "image", "mixed", "text-focused"),
            pattern: fc.constantFrom("cards", "grid", "flow", "split", "spotlight"),
            emphasis: fc.constantFrom("progression", "contrast", "relationship", "scale"),
          }),
          contentLayoutHint: fc.constantFrom("boxes", "bullets", "sequence", "steps", "quotes", "circles", "numbers"),
        }),
        (slide) => {
          const normalized = validateAndNormalizeSlideMetadata(slide);
          
          // Original valid values should be preserved
          expect(normalized.semanticIntent).toBe(slide.semanticIntent);
          expect(normalized.visualStrategy.primary).toBe(slide.visualStrategy.primary);
          expect(normalized.visualStrategy.pattern).toBe(slide.visualStrategy.pattern);
          expect(normalized.visualStrategy.emphasis).toBe(slide.visualStrategy.emphasis);
          expect(normalized.contentLayoutHint).toBe(slide.contentLayoutHint);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should not modify title slides', () => {
    fc.assert(
      fc.property(
        fc.record({
          type: fc.constant("title" as const),
          title: fc.string({ minLength: 5, maxLength: 50 }),
          subtitle: fc.option(fc.string({ minLength: 5, maxLength: 100 }), { nil: undefined }),
        }),
        (slide) => {
          const normalized = validateAndNormalizeSlideMetadata(slide);
          
          // Title slides should pass through unchanged
          expect(normalized).toEqual(slide);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('should validate entire outline with multiple slides', () => {
    fc.assert(
      fc.property(
        fc.record({
          slides: fc.array(partialContentSlideArb, { minLength: 1, maxLength: 10 }),
          metadata: fc.record({
            topic: fc.string({ minLength: 5, maxLength: 100 }),
            totalSlides: fc.integer({ min: 1, max: 20 }),
            tone: fc.string(),
            language: fc.string(),
          }),
        }),
        (outline) => {
          const normalized = validateAndNormalizeOutline(outline);
          
          // All slides should have complete metadata
          for (const slide of normalized.slides) {
            if (slide.type === "content") {
              expect(slide.semanticIntent).toBeDefined();
              expect(slide.visualStrategy).toBeDefined();
              expect(slide.visualStrategy.primary).toBeDefined();
              expect(slide.visualStrategy.pattern).toBeDefined();
              expect(slide.visualStrategy.emphasis).toBeDefined();
            }
          }
        }
      ),
      { numRuns: 50 }
    );
  });

  it('should handle missing visualStrategy fields individually', () => {
    const slideWithPartialVisualStrategy = {
      type: "content" as const,
      title: "Test Slide",
      bulletPoints: ["Point 1", "Point 2"],
      visualStrategy: {
        primary: "diagram",
        // pattern and emphasis missing
      },
    };

    const normalized = validateAndNormalizeSlideMetadata(slideWithPartialVisualStrategy);
    
    expect(normalized.visualStrategy.primary).toBe("diagram");
    expect(normalized.visualStrategy.pattern).toBe("cards");
    expect(normalized.visualStrategy.emphasis).toBe("clarity");
  });

  it('should apply fallback values when metadata is completely missing', () => {
    const slideWithNoMetadata = {
      type: "content" as const,
      title: "Test Slide",
      bulletPoints: ["Point 1", "Point 2", "Point 3"],
    };

    const normalized = validateAndNormalizeSlideMetadata(slideWithNoMetadata);
    
    // Check fallback values
    expect(normalized.semanticIntent).toBe("inform");
    expect(normalized.visualStrategy).toEqual({
      primary: "text-focused",
      pattern: "cards",
      emphasis: "clarity",
    });
  });

  it('should throw error for invalid outline structure', () => {
    const invalidOutline = {
      // Missing slides array
      metadata: { topic: "Test" },
    };

    expect(() => validateAndNormalizeOutline(invalidOutline)).toThrow("Invalid outline structure");
  });

  it('should handle assets/image metadata validation', () => {
    fc.assert(
      fc.property(
        fc.record({
          type: fc.constant("content" as const),
          title: fc.string({ minLength: 5, maxLength: 50 }),
          bulletPoints: fc.array(fc.string({ minLength: 10, maxLength: 100 }), { minLength: 2, maxLength: 6 }),
          assets: fc.record({
            image: fc.record({
              required: fc.option(fc.boolean(), { nil: undefined }),
              orientation: fc.option(fc.constantFrom("landscape", "portrait"), { nil: undefined }),
              pexelsPromptHint: fc.string(),
              aiPromptHint: fc.string(),
            }),
          }),
        }),
        (slide) => {
          const normalized = validateAndNormalizeSlideMetadata(slide);
          
          if (normalized.assets?.image) {
            // required should be a boolean
            expect(typeof normalized.assets.image.required).toBe('boolean');
            
            // orientation should be present
            expect(normalized.assets.image.orientation).toBeDefined();
            expect(['landscape', 'portrait']).toContain(normalized.assets.image.orientation);
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});

/**
 * Integration test: Test fallback behavior with real-world scenarios
 */
describe('Integration: Fallback behavior', () => {
  it('should handle LLM response with missing fields gracefully', () => {
    const llmResponse = {
      slides: [
        {
          type: "title",
          title: "My Presentation",
          subtitle: "A great topic",
        },
        {
          type: "content",
          title: "First Point",
          bulletPoints: ["Detail 1", "Detail 2", "Detail 3"],
          // Missing semanticIntent and visualStrategy
        },
        {
          type: "content",
          title: "Second Point",
          bulletPoints: ["Detail A", "Detail B"],
          semanticIntent: "compare",
          // Missing visualStrategy
        },
        {
          type: "content",
          title: "Third Point",
          bulletPoints: ["Item 1", "Item 2", "Item 3", "Item 4"],
          semanticIntent: "instruct",
          visualStrategy: {
            primary: "diagram",
            // Missing pattern and emphasis
          },
        },
      ],
      metadata: {
        topic: "Test Topic",
        totalSlides: 4,
        tone: "professional",
        language: "english",
      },
    };

    const normalized = validateAndNormalizeOutline(llmResponse);

    // Title slide should be unchanged
    expect(normalized.slides[0]).toEqual(llmResponse.slides[0]);

    // First content slide should have all fallbacks
    expect(normalized.slides[1].semanticIntent).toBe("inform");
    expect(normalized.slides[1].visualStrategy).toEqual({
      primary: "text-focused",
      pattern: "cards",
      emphasis: "clarity",
    });

    // Second content slide should preserve semanticIntent and add visualStrategy
    expect(normalized.slides[2].semanticIntent).toBe("compare");
    expect(normalized.slides[2].visualStrategy).toEqual({
      primary: "text-focused",
      pattern: "cards",
      emphasis: "clarity",
    });

    // Third content slide should preserve what's there and fill in missing
    expect(normalized.slides[3].semanticIntent).toBe("instruct");
    expect(normalized.slides[3].visualStrategy.primary).toBe("diagram");
    expect(normalized.slides[3].visualStrategy.pattern).toBe("cards");
    expect(normalized.slides[3].visualStrategy.emphasis).toBe("clarity");
  });
});
