/**
 * Property-Based Tests for Metadata Extractor
 * 
 * Tests the metadata extraction, normalization, and validation functions
 * using property-based testing with fast-check.
 */

import { describe, it, expect } from "vitest";
import * as fc from "fast-check";
import {
  extractSlideMetadata,
  normalizeSemanticIntent,
  normalizeVisualStrategy,
  validateMetadata,
} from "./metadata-extractor";
import type { SlideMetadata, VisualStrategy } from "../types";

/**
 * **Feature: smart-layout-selection, Property 1: Metadata Completeness**
 * 
 * For any outline slide generated by the system, all required metadata fields
 * (semanticIntent, visualStrategy, contentLayoutHint, assets) must be present
 * with either LLM-provided values or system-generated fallback values.
 * 
 * **Validates: Requirements 1.1, 1.2, 1.3, 1.4, 1.5, 1.6**
 */
describe("Property 1: Metadata Completeness", () => {
  // Arbitrary generators for test data
  
  /**
   * Generates arbitrary semantic intent values (including undefined and invalid)
   */
  const arbitrarySemanticIntent = fc.oneof(
    fc.constant(undefined),
    fc.constantFrom(
      "inform", "compare", "instruct", "emphasize", "narrate",
      "analyze", "demonstrate", "teach", "explain", "describe"
    ),
    fc.string() // Random strings to test normalization
  );
  
  /**
   * Generates arbitrary visual strategy objects (including undefined and partial)
   */
  const arbitraryVisualStrategy = fc.oneof(
    fc.constant(undefined),
    fc.record({
      primary: fc.oneof(
        fc.constant(undefined),
        fc.constantFrom("diagram", "image", "mixed", "text-focused", "text", "visual")
      ),
      pattern: fc.oneof(
        fc.constant(undefined),
        fc.constantFrom("cards", "grid", "flow", "split", "spotlight", "pyramid", "timeline")
      ),
      emphasis: fc.oneof(
        fc.constant(undefined),
        fc.constantFrom("progression", "contrast", "relationship", "scale", "hierarchy", "clarity")
      ),
    }, { requiredKeys: [] }) // Allow partial objects
  );
  
  /**
   * Generates arbitrary image metadata (including undefined and partial)
   */
  const arbitraryImageMetadata = fc.oneof(
    fc.constant(undefined),
    fc.record({
      required: fc.boolean(),
      orientation: fc.constantFrom("landscape", "portrait"),
      pexelsPromptHint: fc.string(),
      aiPromptHint: fc.string(),
    }, { requiredKeys: [] }) // Allow partial objects
  );
  
  /**
   * Generates arbitrary outline slides with various metadata combinations
   */
  const arbitraryOutlineSlide = fc.record({
    type: fc.constantFrom("title", "content"),
    title: fc.string(),
    subtitle: fc.option(fc.string()),
    bulletPoints: fc.option(fc.array(fc.string())),
    semanticIntent: arbitrarySemanticIntent,
    visualStrategy: arbitraryVisualStrategy,
    contentLayoutHint: fc.option(fc.constantFrom(
      "boxes", "bullets", "sequence", "steps", "quotes", "circles", "numbers"
    )),
    image: arbitraryImageMetadata,
    assets: fc.option(fc.record({
      image: arbitraryImageMetadata,
    })),
  }, { requiredKeys: ["type", "title"] });
  
  it("should always return complete metadata with all required fields", () => {
    fc.assert(
      fc.property(arbitraryOutlineSlide, (slide) => {
        const metadata = extractSlideMetadata(slide);
        
        // Check that all required fields are present
        expect(metadata).toBeDefined();
        expect(metadata.semanticIntent).toBeDefined();
        expect(typeof metadata.semanticIntent).toBe("string");
        expect(metadata.semanticIntent.length).toBeGreaterThan(0);
        
        expect(metadata.visualStrategy).toBeDefined();
        expect(metadata.visualStrategy.primary).toBeDefined();
        expect(typeof metadata.visualStrategy.primary).toBe("string");
        expect(metadata.visualStrategy.pattern).toBeDefined();
        expect(typeof metadata.visualStrategy.pattern).toBe("string");
        expect(metadata.visualStrategy.emphasis).toBeDefined();
        expect(typeof metadata.visualStrategy.emphasis).toBe("string");
        
        expect(metadata.assets).toBeDefined();
        expect(typeof metadata.assets).toBe("object");
        
        // contentLayoutHint is optional, so just check it's the right type if present
        if (metadata.contentLayoutHint !== undefined) {
          expect(typeof metadata.contentLayoutHint).toBe("string");
        }
      }),
      { numRuns: 100 } // Run 100 iterations as specified in design doc
    );
  });
  
  it("should provide fallback values when metadata is missing", () => {
    fc.assert(
      fc.property(arbitraryOutlineSlide, (slide) => {
        const metadata = extractSlideMetadata(slide);
        
        // If input had no semanticIntent, should get fallback "inform"
        if (!slide.semanticIntent) {
          expect(metadata.semanticIntent).toBe("inform");
        }
        
        // If input had no visualStrategy, should get fallback values
        if (!slide.visualStrategy) {
          expect(metadata.visualStrategy.primary).toBe("text-focused");
          expect(metadata.visualStrategy.pattern).toBe("cards");
          expect(metadata.visualStrategy.emphasis).toBe("clarity");
        }
      }),
      { numRuns: 100 }
    );
  });
  
  it("should normalize semantic intent to standard values", () => {
    fc.assert(
      fc.property(arbitrarySemanticIntent, (intent) => {
        const normalized = normalizeSemanticIntent(intent);
        
        // Should always return a valid semantic intent
        expect(normalized).toBeDefined();
        expect(typeof normalized).toBe("string");
        expect(normalized.length).toBeGreaterThan(0);
        
        // Should be one of the standard values
        const validIntents = [
          "inform", "compare", "instruct", "emphasize", "narrate",
          "analyze", "demonstrate"
        ];
        expect(validIntents).toContain(normalized);
      }),
      { numRuns: 100 }
    );
  });
  
  it("should normalize visual strategy to complete objects", () => {
    fc.assert(
      fc.property(arbitraryVisualStrategy, (strategy) => {
        const normalized = normalizeVisualStrategy(strategy);
        
        // Should always return a complete VisualStrategy
        expect(normalized).toBeDefined();
        expect(normalized.primary).toBeDefined();
        expect(typeof normalized.primary).toBe("string");
        expect(normalized.pattern).toBeDefined();
        expect(typeof normalized.pattern).toBe("string");
        expect(normalized.emphasis).toBeDefined();
        expect(typeof normalized.emphasis).toBe("string");
        
        // Check valid values for primary
        const validPrimary = ["diagram", "image", "mixed", "text-focused"];
        expect(validPrimary).toContain(normalized.primary);
        
        // Check valid values for pattern
        const validPattern = [
          "cards", "grid", "flow", "split", "spotlight", "pyramid", "timeline"
        ];
        expect(validPattern).toContain(normalized.pattern);
        
        // Check valid values for emphasis
        const validEmphasis = [
          "progression", "contrast", "relationship", "scale", "hierarchy", "clarity"
        ];
        expect(validEmphasis).toContain(normalized.emphasis);
      }),
      { numRuns: 100 }
    );
  });
  
  it("should validate metadata and report completeness", () => {
    fc.assert(
      fc.property(arbitraryOutlineSlide, (slide) => {
        const metadata = extractSlideMetadata(slide);
        const validation = validateMetadata(metadata);
        
        // Since extractSlideMetadata always provides complete metadata,
        // validation should always pass
        expect(validation).toBeDefined();
        expect(validation.valid).toBe(true);
        expect(validation.warnings).toEqual([]);
      }),
      { numRuns: 100 }
    );
  });
  
  it("should handle image metadata from multiple locations", () => {
    fc.assert(
      fc.property(
        fc.record({
          type: fc.constantFrom("title", "content"),
          title: fc.string(),
          image: arbitraryImageMetadata,
          assets: fc.option(fc.record({
            image: arbitraryImageMetadata,
          })),
        }),
        (slide) => {
          const metadata = extractSlideMetadata(slide);
          
          // Should always have assets object
          expect(metadata.assets).toBeDefined();
          
          // If either image or assets.image was provided, should extract it
          if (slide.image || slide.assets?.image) {
            // Should have extracted image metadata
            // (may be undefined if both were undefined, but that's handled)
          }
          
          // If image metadata is present, should be normalized
          if (metadata.assets.image) {
            expect(metadata.assets.image.required).toBeDefined();
            expect(typeof metadata.assets.image.required).toBe("boolean");
            expect(metadata.assets.image.orientation).toBeDefined();
            expect(["landscape", "portrait"]).toContain(metadata.assets.image.orientation);
            expect(metadata.assets.image.pexelsPromptHint).toBeDefined();
            expect(typeof metadata.assets.image.pexelsPromptHint).toBe("string");
            expect(metadata.assets.image.aiPromptHint).toBeDefined();
            expect(typeof metadata.assets.image.aiPromptHint).toBe("string");
          }
        }
      ),
      { numRuns: 100 }
    );
  });
  
  it("should preserve valid LLM-provided values", () => {
    // Test with known valid values
    const validSlide = {
      type: "content" as const,
      title: "Test Slide",
      semanticIntent: "compare",
      visualStrategy: {
        primary: "diagram",
        pattern: "grid",
        emphasis: "contrast",
      },
      contentLayoutHint: "boxes",
    };
    
    const metadata = extractSlideMetadata(validSlide);
    
    // Should preserve the valid values
    expect(metadata.semanticIntent).toBe("compare");
    expect(metadata.visualStrategy.primary).toBe("diagram");
    expect(metadata.visualStrategy.pattern).toBe("grid");
    expect(metadata.visualStrategy.emphasis).toBe("contrast");
    expect(metadata.contentLayoutHint).toBe("boxes");
  });
  
  it("should handle completely empty slides", () => {
    const emptySlide = {
      type: "content" as const,
      title: "",
    };
    
    const metadata = extractSlideMetadata(emptySlide);
    
    // Should still return complete metadata with fallbacks
    expect(metadata.semanticIntent).toBe("inform");
    expect(metadata.visualStrategy.primary).toBe("text-focused");
    expect(metadata.visualStrategy.pattern).toBe("cards");
    expect(metadata.visualStrategy.emphasis).toBe("clarity");
    expect(metadata.assets).toBeDefined();
  });
});
